export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const STOP_LOGIN_LOADING = "STOP_LOGIN_LOADING";
export const LOGOUT = "LOGOUT";
