

export const USER_POSTS_FETCH_REQUESTED = "USER_POSTS_FETCH_REQUESTED";
export const USER_POSTS_FETCH_SUCCEEDED = "USER_POSTS_FETCH_SUCCEEDED";
export const USER_POSTS_FETCH_FAILED = "USER_POSTS_FETCH_FAILED";
export const USER_POSTS_FETCH_CANCEL = "USER_POSTS_FETCH_CANCEL";

export enum UserPostsActionType {
  FETCH_REQUESTED = "FETCH_REQUESTED",
  FETCH_SUCCEEDED = "FETCH_SUCCEEDED",
  FETCH_FAILED = "FETCH_FAILED",
  FETCH_CANCEL = "FETCH_CANCEL"
}

export const SAVE_USER_POSTS = "SAVE_USER_POSTS";
export const SAVE_USER_ALBUMS = "SAVE_USER_ALBUMS";

export const FILES_UPLOADING_START = "FILES_UPLOADING_START";
export const FILES_UPLOADING_PROGRESS = "FILES_UPLOADING_PROGRESS";

export const CHANGE_USERNAME = "CHANGE_USERNAME";
