export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const INCREMENT_ASYNC = "INCREMENT_ASYNC";
export const DECREMENT_ASYNC = "DECREMENT_ASYNC";

export enum CounterActionType  {
  INCREMENT = "INCREMENT",
  DECREMENT = "DECREMENT",
  INCREMENT_ASYNC = "INCREMENT_ASYNC",
  DECREMENT_ASYNC = "DECREMENT_ASYNC"
}